### ISSUE TITLE
No one instrument has a secondary usage

### ISSUE THREAD

**Issue by Athos32** [sinkillerj/ProjectE#1291]
Dear sinkillerj,
Trying to use all strument (Philosofer stone, Destruction Catalist, Dark Matter Pickaxe ...) I have noted that no one instrument have the secondary function( like DM pick with the the DX button of the mouse don't pick up any ore ) or the primary in case of the destruction catalist.
I hope in your reply or update of this mod.
Sorry for my bad english.
Athos

**Comment by williewillus** [comment]
Everyone's reporting this but I cannmot reproduce it :(

**Comment by aslei** [comment]
@williewillus What version of Minecraft/Forge are you using? I can't even get it to work with just MC 1.10.2 and forge (any version available2001-2010).
I also added just enough items and resources to make tests quick, but it doesn't work without it anyways.
This is just with Forge/ProjectE. Just in case it made a difference. Current Forge version is 2010.

`[20:10:45] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at moze_intel.projecte.utils.PlayerHelper.hasBreakPermission(PlayerHelper.java:116) ~[PlayerHelper.class:?]
	at moze_intel.projecte.gameObjs.items.DestructionCatalyst.func_77659_a(DestructionCatalyst.java:82) ~[DestructionCatalyst.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
`

Tried installing it manually(not using multimc) and still having same problem.

**Comment by williewillus** [comment]
This is a 1.10 problem. I have asked @sinkillerj to take it off curse for 1.10 but it will require a recompile to work on 1.10 properly

**Comment by williewillus** [comment]
should be fixed next build
