### ISSUE TITLE
[1.9]Cannot use right click on many items

### ISSUE THREAD

**Issue by xun468** [sinkillerj/ProjectE#1319]
Hey, so I'm trying to use the right click functionality on various project e items (ex destruction catalyst, catalytic lens, etc) and they are throwing fatal errors. This is with ProjectE-1.9.4-PE1.0.5B running on 1.10.2 and java 8. I might dumb and be missing a dependency though

Here is one of the errors 
[20:29:13] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
    at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
    at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
    at moze_intel.projecte.utils.PlayerHelper.hasBreakPermission(PlayerHelper.java:116) ~[PlayerHelper.class:?]
    at moze_intel.projecte.gameObjs.items.DestructionCatalyst.func_77659_a(DestructionCatalyst.java:82) ~[DestructionCatalyst.class:?]
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
    at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
    at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
    at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
    ... 5 more

**Comment by williewillus** [comment]
PE doesn't work on 1.10 yet
